"""Configuration, integration and operator-support commands."""

from .types import CommandDef

COMMANDS: list[CommandDef] = [
    # Configuration
    CommandDef("config", "Show current configuration", "Configuration", cli_only=True),
    CommandDef(
        "model",
        "Switch model for this session",
        "Configuration",
        aliases=("provider",),
        args_hint="[model] [--provider name] [--global] [--refresh]",
    ),
    CommandDef(
        "codex-runtime",
        "Toggle codex app-server runtime for OpenAI/Codex models",
        "Configuration",
        aliases=("codex_runtime",),
        args_hint="[auto|codex_app_server]",
    ),
    CommandDef(
        "gquota", "Show Google Gemini Code Assist quota usage", "Info", cli_only=True
    ),
    CommandDef(
        "style",
        "Switch forecast style overlay; forecast protocol stays authoritative",
        "Configuration",
        aliases=("personality",),
        args_hint="[name]",
    ),
    CommandDef(
        "statusbar",
        "Toggle the context/model status bar",
        "Configuration",
        cli_only=True,
        aliases=("sb",),
    ),
    CommandDef(
        "verbose",
        "Cycle tool progress display: off -> new -> all -> verbose",
        "Configuration",
        cli_only=True,
        gateway_config_gate="display.tool_progress_command",
    ),
    CommandDef(
        "footer",
        "Toggle gateway runtime-metadata footer on final replies",
        "Configuration",
        args_hint="[on|off|status]",
        subcommands=("on", "off", "status"),
    ),
    CommandDef(
        "yolo",
        "Toggle YOLO mode (skip all dangerous command approvals)",
        "Configuration",
    ),
    CommandDef(
        "reasoning",
        "Manage reasoning effort and display",
        "Configuration",
        args_hint="[level|show|hide]",
        subcommands=(
            "none",
            "minimal",
            "low",
            "medium",
            "high",
            "xhigh",
            "show",
            "hide",
            "on",
            "off",
        ),
    ),
    CommandDef(
        "fast",
        "Toggle fast mode — OpenAI Priority Processing / Anthropic Fast Mode (Normal/Fast)",
        "Configuration",
        args_hint="[normal|fast|status]",
        subcommands=("normal", "fast", "status", "on", "off"),
    ),
    CommandDef(
        "skin",
        "Show or change the display skin/theme",
        "Configuration",
        cli_only=True,
        args_hint="[name]",
    ),
    CommandDef(
        "indicator",
        "Pick the TUI busy-indicator style",
        "Configuration",
        cli_only=True,
        args_hint="[markers|emoji|unicode|ascii]",
        subcommands=("markers", "emoji", "unicode", "ascii"),
    ),
    CommandDef(
        "voice",
        "Toggle optional voice compatibility mode",
        "Compatibility",
        args_hint="[on|off|tts|status]",
        subcommands=("on", "off", "tts", "status"),
    ),
    CommandDef(
        "busy",
        "Control what Enter does while the forecast desk is working",
        "Configuration",
        cli_only=True,
        args_hint="[queue|steer|interrupt|status]",
        subcommands=("queue", "steer", "interrupt", "status"),
    ),
    # Tools & Skills
    CommandDef(
        "tools",
        "Manage tools: /tools [list|disable|enable] [name...]",
        "Tools & Skills",
        args_hint="[list|disable|enable] [name...]",
        cli_only=True,
    ),
    CommandDef("toolsets", "List available toolsets", "Tools & Skills", cli_only=True),
    CommandDef(
        "skills",
        "Search, install, inspect, or manage optional skill playbooks",
        "Compatibility",
        cli_only=True,
        subcommands=("search", "browse", "inspect", "install"),
    ),
    CommandDef(
        "bundles",
        "List optional skill bundles (aliases /<name> for multiple skills)",
        "Compatibility",
    ),
    CommandDef(
        "learn",
        "Learn a reusable skill from anything you describe (dirs, URLs, this chat, notes)",
        "Tools & Skills",
        args_hint="<what to learn from>",
    ),
    CommandDef(
        "cron",
        "Manage scheduled tasks",
        "Tools & Skills",
        cli_only=True,
        args_hint="[subcommand]",
        subcommands=(
            "list",
            "add",
            "create",
            "edit",
            "pause",
            "resume",
            "run",
            "remove",
        ),
    ),
    CommandDef(
        "curator",
        "Optional background skill maintenance (status, run, pin, archive, list-archived)",
        "Compatibility",
        args_hint="[subcommand]",
        subcommands=(
            "status",
            "run",
            "pause",
            "resume",
            "pin",
            "unpin",
            "restore",
            "list-archived",
        ),
    ),
    CommandDef(
        "kanban",
        "Optional multi-profile collaboration board (tasks, links, comments)",
        "Compatibility",
        args_hint="[subcommand]",
        subcommands=(
            "init",
            "boards",
            "create",
            "list",
            "ls",
            "show",
            "assign",
            "reclaim",
            "reassign",
            "diagnostics",
            "diag",
            "link",
            "unlink",
            "claim",
            "comment",
            "complete",
            "edit",
            "block",
            "unblock",
            "archive",
            "tail",
            "dispatch",
            "stats",
            "notify-subscribe",
            "notify-list",
            "notify-unsubscribe",
            "log",
            "runs",
            "heartbeat",
            "assignees",
            "context",
            "specify",
            "gc",
        ),
    ),
    CommandDef(
        "reload",
        "Reload .env variables into the running session",
        "Tools & Skills",
        cli_only=True,
    ),
    CommandDef(
        "reload-mcp",
        "Reload MCP servers from config",
        "Tools & Skills",
        aliases=("reload_mcp",),
    ),
    CommandDef(
        "reload-skills",
        "Re-scan forecast skill directories for newly installed or removed skills",
        "Tools & Skills",
        aliases=("reload_skills",),
    ),
    CommandDef(
        "browser",
        "Connect browser tools to your live Chromium-family browser via CDP",
        "Tools & Skills",
        cli_only=True,
        args_hint="[connect|disconnect|status]",
        subcommands=("connect", "disconnect", "status"),
    ),
    CommandDef(
        "plugins",
        "List installed plugins and their status",
        "Tools & Skills",
        cli_only=True,
    ),
    # Info
    CommandDef(
        "commands",
        "Browse all commands and skills (paginated)",
        "Info",
        gateway_only=True,
        args_hint="[page]",
    ),
    CommandDef("help", "Show available commands", "Info"),
    CommandDef(
        "restart",
        "Gracefully restart the gateway after draining active runs",
        "Session",
        gateway_only=True,
    ),
    CommandDef(
        "usage", "Show token usage and rate limits for the current session", "Info"
    ),
    CommandDef(
        "insights", "Show usage insights and analytics", "Info", args_hint="[days]"
    ),
    CommandDef(
        "platforms",
        "Show optional gateway/messaging platform status",
        "Compatibility",
        cli_only=True,
        aliases=("gateway",),
    ),
    CommandDef(
        "platform",
        "Pause, resume, or list a failing gateway platform",
        "Info",
        gateway_only=True,
        args_hint="<pause|resume|list> [name]",
    ),
    CommandDef(
        "copy",
        "Copy the last forecast response to clipboard",
        "Info",
        cli_only=True,
        args_hint="[number]",
    ),
    CommandDef(
        "paste", "Attach clipboard image from your clipboard", "Info", cli_only=True
    ),
    CommandDef(
        "image",
        "Attach a local image file for your next prompt",
        "Info",
        cli_only=True,
        args_hint="<path>",
    ),
    CommandDef(
        "update",
        "Update the app; with args, append a forecast update",
        "Info",
        args_hint="[row|id|words -- --probability <p> --rationale <why>]",
    ),
    CommandDef(
        "debug",
        "Upload debug report (system info + logs) and get shareable links",
        "Info",
    ),
    # Exit
    CommandDef(
        "quit",
        "Exit the CLI (use --delete to also remove session history)",
        "Exit",
        cli_only=True,
        aliases=("exit",),
        args_hint="[--delete]",
    ),
]
