"""Forecast-desk and session workflow commands."""

from .types import CommandDef

FORECAST_DESK_SUBCOMMANDS: tuple[str, ...] = (
    "about",
    "status",
    "doctor",
    "sources",
    "new",
    "list",
    "show",
    "update",
    "ingest",
    "import",
    "tournament",
    "plugins",
    "research",
    "base-rate",
    "model",
    "quorum",
    "api-key",
    "bayes",
    "protocol",
    "agent",
    "assumption",
    "reference-class",
    "evidence",
    "resolve",
    "score",
    "scores",
    "postmortem",
    "lesson",
    "lessons",
    "correction",
    "resolver",
    "calibration",
    "errors",
    "review",
    "schedule",
    "watch",
    "alerts",
    "autopilot",
    "self-check",
    "backtest",
    "performance",
    "readiness",
    "pilot-report",
    "pilot-cohort",
    "pilot-aggregate",
    "pilot-bundle",
    "export",
)

COMMANDS: list[CommandDef] = [
    # Session
    CommandDef(
        "new",
        "Start a new forecast session (fresh session ID + history)",
        "Session",
        aliases=("reset",),
        args_hint="[name]",
    ),
    CommandDef(
        "topic",
        "Enable or inspect Telegram DM topic sessions",
        "Session",
        gateway_only=True,
        args_hint="[off|help|session-id]",
    ),
    CommandDef(
        "clear",
        "Clear screen and start a new forecast session",
        "Session",
        cli_only=True,
    ),
    CommandDef(
        "redraw",
        "Force a full UI repaint (recovers from terminal drift)",
        "Session",
        cli_only=True,
    ),
    CommandDef("history", "Show forecast transcript history", "Session", cli_only=True),
    CommandDef(
        "save", "Save the current forecast transcript", "Session", cli_only=True
    ),
    CommandDef("retry", "Retry the last forecast note", "Session"),
    CommandDef("undo", "Remove the last user/forecaster exchange", "Session"),
    CommandDef(
        "title",
        "Set a title for the current forecast session",
        "Session",
        args_hint="[name]",
    ),
    CommandDef(
        "handoff",
        "Hand off this forecast session to an optional messaging compatibility surface",
        "Compatibility",
        args_hint="<platform>",
        cli_only=True,
    ),
    CommandDef(
        "branch",
        "Branch the current forecast session (explore a different path)",
        "Session",
        aliases=("fork",),
        args_hint="[name]",
    ),
    CommandDef(
        "compress",
        "Manually compress forecast transcript context",
        "Session",
        args_hint="[focus topic]",
    ),
    CommandDef(
        "rollback",
        "List or restore filesystem checkpoints",
        "Session",
        args_hint="[number]",
    ),
    CommandDef(
        "snapshot",
        "Create or restore runtime config/state snapshots",
        "Session",
        cli_only=True,
        aliases=("snap",),
        args_hint="[create|restore <id>|prune]",
    ),
    CommandDef("stop", "Kill all running background processes", "Session"),
    CommandDef(
        "approve",
        "Approve a pending dangerous command",
        "Session",
        gateway_only=True,
        args_hint="[session|always]",
    ),
    CommandDef(
        "deny", "Deny a pending dangerous command", "Session", gateway_only=True
    ),
    CommandDef(
        "background",
        "Run a forecast note in the background",
        "Session",
        aliases=("bg", "btw"),
        args_hint="<forecast note>",
    ),
    CommandDef(
        "agents",
        "Show active agents and running forecast tasks",
        "Session",
        aliases=("tasks",),
    ),
    CommandDef(
        "queue",
        "Queue a forecast note for the next turn (doesn't interrupt)",
        "Session",
        aliases=("q",),
        args_hint="<forecast note>",
    ),
    CommandDef(
        "steer",
        "Inject a forecast note after the next tool call without interrupting",
        "Session",
        args_hint="<forecast note>",
    ),
    CommandDef(
        "goal",
        "Set a standing goal the forecaster works on across turns until achieved",
        "Session",
        args_hint="[text | pause | resume | clear | status]",
    ),
    CommandDef(
        "subgoal",
        "Add or manage extra criteria on the active goal",
        "Session",
        args_hint="[text | remove N | clear]",
    ),
    CommandDef("status", "Show forecast session info", "Session"),
    CommandDef(
        "whoami",
        "Show your slash command access (admin / user)",
        "Info",
        gateway_only=True,
    ),
    CommandDef("profile", "Show active profile name and home directory", "Info"),
    CommandDef(
        "sethome",
        "Set this conversation as the scheduled forecast-review delivery channel",
        "Session",
        gateway_only=True,
        aliases=("set-home",),
    ),
    CommandDef(
        "resume",
        "Resume a previously-named forecast session",
        "Session",
        args_hint="[name]",
    ),
    # Forecast desk
    CommandDef("sessions", "Browse and resume previous forecast sessions", "Session"),
    CommandDef(
        "questions",
        "Show current forecast questions and headline probabilities",
        "Forecast Desk",
        aliases=("book", "qbook"),
        args_hint="[row|list N|words]",
        cli_only=True,
    ),
    CommandDef(
        "ledger",
        "Browse forecast ledger views without remembering forecast ids",
        "Forecast Desk",
        aliases=("store", "state"),
        args_hint="[view|search words]",
        cli_only=True,
    ),
    CommandDef(
        "find",
        "Search forecast questions by title, topic, or domain",
        "Forecast Desk",
        aliases=("search-forecasts", "lookup"),
        args_hint="<words>",
        cli_only=True,
    ),
    CommandDef(
        "open",
        "Open a forecast by row, id, short id, or words",
        "Forecast Desk",
        aliases=("question", "show-forecast"),
        args_hint="<row|id|words>",
        cli_only=True,
    ),
    CommandDef(
        "note",
        "Add evidence to a forecast found by row or words",
        "Forecast Desk",
        aliases=("evidence-for", "note-for"),
        args_hint="<row|words> -- <evidence>",
        cli_only=True,
    ),
    CommandDef(
        "revise",
        "Update a forecast found by row or words",
        "Forecast Desk",
        aliases=("update-for", "updateq"),
        args_hint="<row|words> -- <args>",
        cli_only=True,
    ),
    CommandDef(
        "forecast",
        "Open the interactive forecasts workspace (or run lifecycle subcommands)",
        "Forecast Desk",
        aliases=("forecasts", "desk"),
        args_hint="[status|subcommand|id]",
        cli_only=True,
        subcommands=FORECAST_DESK_SUBCOMMANDS,
    ),
    CommandDef(
        "api-key",
        "Manage data-provider API keys (FRED, EIA, web search, …)",
        "Forecast Desk",
        aliases=("apikey", "api-keys", "keys"),
        args_hint="[list|show|set|unset] [provider] [value]",
        cli_only=True,
        subcommands=("list", "show", "set", "unset"),
    ),
]
