#!/usr/bin/env python3
"""Generate the typed News catalog from reviewed, checked-in feed metadata.

Run without network access: python3 scripts/gen-news-catalog.py [--check]
See ui-tui/src/content/README.md for source qualification and attribution.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from urllib.parse import urlsplit, urlunsplit

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "ui-tui/src/content/newsFeeds.json"
OUTPUT = ROOT / "ui-tui/src/content/newsFeedCatalog.ts"


def render(feeds: list[dict[str, str]]) -> str:
    """Reject malformed metadata and duplicate URLs before generating code."""
    seen: set[str] = set()
    for feed in feeds:
        if set(feed) != {"category", "title", "url", "description"}:
            raise ValueError("Feed fields must be category, title, url, description")
        if any(not isinstance(value, str) for value in feed.values()):
            raise ValueError("Feed metadata must contain strings")
        if any(not feed[key].strip() for key in ("category", "title", "url")):
            raise ValueError("Feed category, title and URL must not be empty")
        url = urlsplit(feed["url"])
        if (
            url.scheme not in {"http", "https"}
            or not url.hostname
            or url.username
            or url.password
            or url.fragment
            or any(char.isspace() for char in feed["url"])
        ):
            raise ValueError(f"Invalid public feed URL: {feed['url']}")
        # Schemes/hosts are case-insensitive; paths and query values are not.
        key = urlunsplit((
            url.scheme,
            url.netloc.lower(),
            url.path.rstrip("/"),
            url.query,
            "",
        ))
        if key in seen:
            raise ValueError(f"Duplicate feed URL: {feed['url']}")
        seen.add(key)
    ordered = sorted(
        feeds, key=lambda feed: (feed["category"].lower(), feed["title"].lower())
    )
    categories = sorted({feed["category"] for feed in feeds}, key=str.lower)
    return (
        "// AUTO-GENERATED by scripts/gen-news-catalog.py — do not edit by hand.\n"
        "// Source: newsFeeds.json; attribution and qualification: README.md.\n"
        f"// {len(feeds)} feeds across {len(categories)} categories.\n\n"
        "export interface CatalogFeed {\n"
        "  category: string\n  title: string\n  url: string\n  description: string\n}\n\n"
        f"export const FEED_CATEGORIES: string[] = {json.dumps(categories, ensure_ascii=False)}\n\n"
        "export const FEED_CATALOG: CatalogFeed[] = "
        + "[\n"
        + ",\n".join("  " + json.dumps(feed, ensure_ascii=False) for feed in ordered)
        + "\n]"
        + "\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="Fail if generated output is stale"
    )
    args = parser.parse_args()
    rendered = render(json.loads(SOURCE.read_text(encoding="utf-8")))
    if args.check:
        if OUTPUT.read_text(encoding="utf-8") != rendered:
            parser.exit(
                1, "News catalog is stale; run python3 scripts/gen-news-catalog.py\n"
            )
    else:
        OUTPUT.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
