#!/usr/bin/env python3
"""Convert an image into a high-resolution, theme-agnostic luminance bitmap for
the TUI header.

We store per-pixel LUMINANCE (0-255), not colour — so the header can be tinted
to whatever theme colour the user picks, at render time. The TUI renders it
with the upper-half-block glyph (▀): each cell stacks two vertical pixels
(top = foreground, bottom = background) for 2x vertical resolution, downscaling
the stored bitmap to whatever width fits the terminal.

Rows are base64-encoded bytes (one luminance byte per pixel) to keep the module
small. Near-black pixels are dropped to transparent at RENDER time (after
downscale) so the art floats on the terminal background in any theme.

Usage:
    python scripts/gen-header.py <input.png> --width 144 \
        --name OUTRIDER_HEADER --out src/content/outriderHeader.ts [--preview]
"""
from __future__ import annotations

import argparse
import base64
import json
import sys

from PIL import Image


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("src")
    ap.add_argument("--width", type=int, default=144, help="stored bitmap width in px (native/max)")
    ap.add_argument("--name", default="OUTRIDER_HEADER")
    ap.add_argument("--out", default=None)
    ap.add_argument("--preview", action="store_true")
    ap.add_argument("--preview-thresh", type=int, default=22)
    args = ap.parse_args()

    img = Image.open(args.src).convert("RGB")
    w0, h0 = img.size
    aspect = w0 / h0
    h_px = round(args.width / aspect)
    if h_px % 2:
        h_px += 1
    # High-quality downscale, then perceptual luminance per pixel.
    img = img.resize((args.width, h_px), Image.LANCZOS)
    px = img.load()

    rows_b64: list[str] = []
    lum_rows: list[list[int]] = []
    for y in range(h_px):
        row = bytearray(args.width)
        lr = []
        for x in range(args.width):
            r, g, b = px[x, y]
            lum = int(0.2126 * r + 0.7152 * g + 0.0722 * b + 0.5)
            lum = 255 if lum > 255 else lum
            row[x] = lum
            lr.append(lum)
        rows_b64.append(base64.b64encode(bytes(row)).decode("ascii"))
        lum_rows.append(lr)

    data = {"w": args.width, "h": h_px, "rows": rows_b64}

    if args.preview:
        # Render a quick truecolour teal-tinted preview at native size.
        th = args.preview_thresh
        for ry in range(h_px // 2):
            line = ""
            for x in range(args.width):
                top = lum_rows[2 * ry][x]
                bot = lum_rows[2 * ry + 1][x] if (2 * ry + 1) < h_px else 0
                to, bo = top >= th, bot >= th

                def tint(L: int) -> str:
                    t = L / 255.0
                    if t < 0.78:
                        k = t / 0.78
                        r, g, b = int(20 * k), int(200 * k), int(150 * k)
                    else:
                        k = (t - 0.78) / 0.22
                        r = int(20 + (255 - 20) * k)
                        g = int(200 + (255 - 200) * k)
                        b = int(150 + (255 - 150) * k)
                    return f"\x1b[38;2;{r};{g};{b}m"

                if to and bo:
                    fg = tint(top)
                    bgL = bot / 255.0
                    if bgL < 0.78:
                        k = bgL / 0.78
                        br, bg, bb = int(20 * k), int(200 * k), int(150 * k)
                    else:
                        k = (bgL - 0.78) / 0.22
                        br, bg, bb = int(20 + 235 * k), int(200 + 55 * k), int(150 + 105 * k)
                    line += f"{fg}\x1b[48;2;{br};{bg};{bb}m▀\x1b[0m"
                elif to:
                    line += f"{tint(top)}▀\x1b[0m"
                elif bo:
                    line += f"{tint(bot)}▄\x1b[0m"
                else:
                    line += " "
            sys.stdout.write(line + "\n")
        sys.stderr.write(f"\nnative {args.width}x{h_px}px ({args.width}x{h_px // 2} cells)\n")

    body = json.dumps(data, separators=(",", ":"))
    ts = (
        f"// {args.name} — high-res LUMINANCE bitmap of {args.src.split('/')[-1]} "
        f"(theme-tinted at render time).\n"
        f"// Generated by ui-tui/scripts/gen-header.py — do not hand-edit.\n"
        f"// rows[] are base64 bytes, one luminance value (0-255) per pixel; width w, height h px.\n"
        f"export interface LumBitmap {{ w: number; h: number; rows: string[] }}\n\n"
        f"export const {args.name}: LumBitmap = {body}\n"
    )
    if args.out:
        with open(args.out, "w", encoding="utf-8") as f:
            f.write(ts)
        sys.stderr.write(f"wrote {args.out} ({len(ts)} bytes)\n")
    else:
        sys.stdout.write(ts)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
